name: validatietool

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - geopandas
  - jupyter
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - numpy
  - pytest
  - pytest-cov
  - rasterio
  - rasterstats
  - rtree